version: "2.19.1"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      #Externo:Interno
      - "5050:5000"
    environment:
      - GREETINGS=Hello Rubiko Tech!
    networks:
      - mainnetwork

  curl:
    depends_on:
      - web
    image: curlimages/curl
    command: ["curl", "http://web:5000/health"]
    networks:
      - mainnetwork

networks:
  mainnetwork:
    driver: bridge
    name: mainnetwork
